"""Generates notebooks/model-smoke/model-smoke.ipynb — does the model actually load?

Not a submission. Consumes no submission slot. Answers the one question that
still stands between this repo and a scored run: whether Gemma-4-31B really
loads and really answers on the Kaggle card, and what a single call costs.

Why it is worth a kernel run of its own: the submission notebook's readiness
gate performs exactly this check, but it performs it *during the scored run*.
If the weights fail to load there — OOM, a transformers/checkpoint mismatch,
anything — the gate exits non-zero and the notebook stops, which is a loud
failure rather than a silent one but still a zero. Finding that out here
costs a few minutes of GPU quota instead of a submission.

It also produces the number nobody has: real per-call latency. `max_actions`
is 400 and has never been calibrated against a real Gemma call, while ~25
games' worth of calls have to fit in Kaggle's ~9 hours.

This deliberately runs `build_notebook.READINESS_GATE_SOURCE` verbatim rather
than a copy. A smoke test of *similar* code would leave open the one thing it
is meant to close.

    python scripts/build_model_smoke_notebook.py
    KAGGLE_API_TOKEN=$(cat .kaggle/access_token) \
        kaggle kernels push -p notebooks/model-smoke --accelerator NvidiaRtxPro6000
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

import build_notebook  # noqa: E402

SMOKE_DIR = ROOT / "notebooks" / "model-smoke"
NOTEBOOK_PATH = SMOKE_DIR / "model-smoke.ipynb"
METADATA_PATH = SMOKE_DIR / "kernel-metadata.json"

KERNEL_SLUG = "zerx-model-smoke"


def build() -> dict:
    intro = build_notebook.markdown_cell(
        "# zerx — does the model actually load?\n\n"
        "Not a submission; consumes no submission slot. Loads Gemma-4-31B in "
        "bf16 from the attached Kaggle model and runs one real generation, "
        "using `scripts/build_notebook.py`'s readiness gate **verbatim** — the "
        "same code the scored run executes.\n\n"
        "Reports: the GPU actually allocated, whether the weights load, "
        "per-call latency, and that latency projected against the ~9h kernel "
        "limit. Generated by `scripts/build_model_smoke_notebook.py`."
    )

    # The gate imports `zerx.config` and `zerx.model_backend`, so the package
    # has to exist here exactly as the submission bundles it — including the
    # rule that `zerx/backends/` is never shipped.
    zerx_bodies = [(p, p.read_text(encoding="utf-8")) for p in build_notebook.zerx_bundle_files()]

    mkdir_cell = build_notebook.code_cell(
        "import os\n"
        "os.makedirs('/tmp/zerx', exist_ok=True)"
    )
    zerx_cells = [
        build_notebook.code_cell(f"%%writefile /tmp/zerx/{path.name}\n" + body)
        for path, body in zerx_bodies
    ]
    gate_cell = build_notebook.code_cell(
        "%%writefile /tmp/zerx_readiness_gate.py\n" + build_notebook.READINESS_GATE_SOURCE
    )

    run_cell = build_notebook.code_cell(
        dedent(
            """\
            import os, subprocess, sys

            # Same subprocess isolation the submission uses: the gate loads
            # 62.58 GB, and a notebook kernel still holding that is exactly the
            # problem the isolation exists to avoid.
            result = subprocess.run(
                [sys.executable, '/tmp/zerx_readiness_gate.py'],
                cwd='/tmp',
                env={**os.environ,
                     'PYTHONPATH': '/tmp',
                     'ZERX_BACKEND': 'BACKEND_LITERAL',
                     'ZERX_PLATFORM': 'PLATFORM_LITERAL',
                     'ZERX_MODEL_PATH': 'MODEL_DIR_LITERAL'},
            )
            print("gate exit code:", result.returncode)
            if result.returncode != 0:
                raise SystemExit(
                    "The model did not load or did not answer. This is the "
                    "failure worth finding here rather than inside a scored run."
                )
            print("The submission's readiness gate passes on real hardware.")
            """
        )
        .replace("BACKEND_LITERAL", build_notebook.ZERX_BACKEND)
        .replace("PLATFORM_LITERAL", build_notebook.ZERX_PLATFORM)
        .replace("MODEL_DIR_LITERAL", build_notebook.KAGGLE_MODEL_DIR or "")
    )

    return {
        "metadata": {
            "kernelspec": {"language": "python", "display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python", "file_extension": ".py"},
            "kaggle": {
                "accelerator": build_notebook._ACCELERATORS[build_notebook.ACCELERATOR]["name"],
                "isInternetEnabled": False,
                "isGpuEnabled": True,
                "language": "python",
                "sourceType": "notebook",
            },
        },
        "nbformat_minor": 4,
        "nbformat": 4,
        "cells": [intro, mkdir_cell, *zerx_cells, gate_cell, run_cell],
    }


def build_metadata() -> dict:
    submission_meta = json.loads(
        build_notebook.METADATA_PATH.read_text(encoding="utf-8")
    )
    return {
        "id": f"{submission_meta['id'].split('/')[0]}/{KERNEL_SLUG}",
        "title": "zerx — model load smoke",
        "code_file": "model-smoke.ipynb",
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        "enable_gpu": True,
        "enable_tpu": False,
        "enable_internet": False,
        "keywords": [],
        "dataset_sources": [],
        "kernel_sources": [],
        # No competition source: this loads a model, it does not play a game.
        "competition_sources": [],
        "model_sources": [build_notebook.MODEL_SOURCE],
    }


def main() -> None:
    SMOKE_DIR.mkdir(parents=True, exist_ok=True)
    NOTEBOOK_PATH.write_text(json.dumps(build(), indent=1), encoding="utf-8")
    METADATA_PATH.write_text(
        json.dumps(build_metadata(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"[build_model_smoke_notebook] Wrote {NOTEBOOK_PATH.relative_to(ROOT)}")
    print(f"[build_model_smoke_notebook] Wrote {METADATA_PATH.relative_to(ROOT)}")
    flag = build_notebook.push_accelerator_flag()
    print(f"[build_model_smoke_notebook] Push with:  kaggle kernels push "
          f"-p notebooks/model-smoke --accelerator {flag}")


if __name__ == "__main__":
    main()
