"""Generates notebooks/model-smoke/model-smoke.ipynb — does the model actually load?

Not a submission. Consumes no submission slot. Answers the one question that
still stands between this repo and a scored run: whether Gemma-4-31B really
loads and really answers on the Kaggle card, and what a single call costs.

Why it is worth a kernel run of its own: the submission notebook's readiness
gate performs exactly this check, but it performs it *during the scored run*.
If the weights fail to load there — OOM, a transformers/checkpoint mismatch,
anything — the gate exits non-zero and the notebook stops, which is a loud
failure rather than a silent one but still a zero. Finding that out here
costs a few minutes of GPU quota instead of a submission.

It also produces the number nobody has: real per-call latency. `max_actions`
is 400 and has never been calibrated against a real Gemma call, while ~25
games' worth of calls have to fit in Kaggle's ~9 hours.

This deliberately runs `build_notebook.READINESS_GATE_SOURCE` verbatim rather
than a copy. A smoke test of *similar* code would leave open the one thing it
is meant to close.

    python scripts/build_model_smoke_notebook.py
    KAGGLE_API_TOKEN=$(cat .kaggle/access_token) \
        kaggle kernels push -p notebooks/model-smoke --accelerator NvidiaRtxPro6000
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

import build_notebook  # noqa: E402

SMOKE_DIR = ROOT / "notebooks" / "model-smoke"
NOTEBOOK_PATH = SMOKE_DIR / "model-smoke.ipynb"
METADATA_PATH = SMOKE_DIR / "kernel-metadata.json"

# Must be the slug Kaggle derives from the title below ("zerx — model load
# smoke"), not an independently chosen name. When the two disagree Kaggle
# creates the kernel under the title-derived slug and warns rather than
# failing; the next push then 409s against an id that does not exist.
KERNEL_SLUG = "zerx-model-load-smoke"


def build() -> dict:
    intro = build_notebook.markdown_cell(
        "# zerx — does the model actually load?\n\n"
        "Not a submission; consumes no submission slot. Loads Gemma-4-31B in "
        "bf16 from the attached Kaggle model and runs one real generation, "
        "using `scripts/build_notebook.py`'s readiness gate **verbatim** — the "
        "same code the scored run executes.\n\n"
        "Reports: the GPU actually allocated, whether the weights load, "
        "per-call latency, and that latency projected against the ~9h kernel "
        "limit. Generated by `scripts/build_model_smoke_notebook.py`."
    )

    # The gate imports `zerx.config` and `zerx.model_backend`, so the package
    # has to exist here exactly as the submission bundles it — including the
    # rule that `zerx/backends/` is never shipped.
    zerx_bodies = [(p, p.read_text(encoding="utf-8")) for p in build_notebook.zerx_bundle_files()]

    # Same offline transformers install the submission performs, verbatim:
    # a smoke test of a different install would prove nothing about it.
    transformers_cell = build_notebook.code_cell(
        build_notebook.TRANSFORMERS_INSTALL_SOURCE
    )

    mkdir_cell = build_notebook.code_cell(
        "import os\n"
        "os.makedirs('/tmp/zerx', exist_ok=True)"
    )
    zerx_cells = [
        build_notebook.code_cell(
            f"%%writefile /tmp/zerx/{path.name}\n" + build_notebook.writefile_body(body)
        )
        for path, body in zerx_bodies
    ]
    gate_cell = build_notebook.code_cell(
        "%%writefile /tmp/zerx_readiness_gate.py\n" + build_notebook.READINESS_GATE_SOURCE
    )

    # Runs BEFORE the gate, and never raises. The gate's job is a verdict; this
    # cell's job is to leave behind enough detail to act on a failure without
    # spending another run guessing. The first attempt died on
    # `ValueError: ... model type 'gemma4' but Transformers does not recognize
    # this architecture`, and the answer to "can that be worked around" lives
    # entirely in facts this cell prints: what the checkpoint declares, what
    # this transformers knows, and whether the checkpoint carries its own
    # modeling code (which `trust_remote_code=True` could then load).
    diagnostic_cell = build_notebook.code_cell(
        dedent(
            """\
            import json, os

            MODEL_DIR = "MODEL_DIR_LITERAL"

            print("=== every file in the model directory ===")
            # The environment probe only ever listed .safetensors/.bin/.gguf/.json,
            # so a bundled modeling_*.py would have been invisible to it.
            for root, _dirs, files in os.walk(MODEL_DIR):
                for name in sorted(files):
                    size = os.path.getsize(os.path.join(root, name))
                    print(f"  {os.path.relpath(os.path.join(root, name), MODEL_DIR):50} "
                          f"{size/1e6:10.1f} MB")

            print()
            print("=== what the checkpoint declares ===")
            try:
                with open(os.path.join(MODEL_DIR, "config.json")) as handle:
                    cfg = json.load(handle)
                for key in ("model_type", "architectures", "torch_dtype",
                            "auto_map", "transformers_version"):
                    print(f"  {key}: {cfg.get(key)}")
            except Exception as exc:
                print("  could not read config.json:", exc)

            print()
            print("=== what this transformers knows ===")
            try:
                import transformers
                from transformers.models.auto.configuration_auto import CONFIG_MAPPING_NAMES
                print("  transformers:", transformers.__version__)
                declared = cfg.get("model_type") if "cfg" in dir() else None
                print(f"  recognises {declared!r}:", declared in CONFIG_MAPPING_NAMES)
                print("  gemma-family model types it does know:",
                      sorted(n for n in CONFIG_MAPPING_NAMES if "gemma" in n))
            except Exception as exc:
                print("  introspection failed:", exc)
            """
        ).replace("MODEL_DIR_LITERAL", build_notebook.KAGGLE_MODEL_DIR or "")
    )

    run_cell = build_notebook.code_cell(
        dedent(
            """\
            import os, subprocess, sys

            # Same subprocess isolation the submission uses: the gate loads
            # 62.58 GB, and a notebook kernel still holding that is exactly the
            # problem the isolation exists to avoid.
            result = subprocess.run(
                [sys.executable, '/tmp/zerx_readiness_gate.py'],
                cwd='/tmp',
                env={**os.environ,
                     'PYTHONPATH': '/tmp',
                     'ZERX_BACKEND': 'BACKEND_LITERAL',
                     'ZERX_PLATFORM': 'PLATFORM_LITERAL',
                     'ZERX_MODEL_PATH': 'MODEL_DIR_LITERAL'},
                capture_output=True, text=True,
            )
            print(result.stdout)
            if result.stderr:
                print("--- gate stderr ---")
                print(result.stderr[-4000:])
            print("gate exit code:", result.returncode)

            # Persist the verdict to /kaggle/working as well as stdout. The
            # kernel log endpoint has come back empty on a COMPLETE run, and a
            # result that only exists in a log we cannot always fetch is a
            # result we may have to pay for twice -- the probe's probe.json
            # downloaded reliably when the log did not.
            import json
            with open('/kaggle/working/smoke.json', 'w') as handle:
                json.dump({
                    "gate_returncode": result.returncode,
                    "gate_stdout": result.stdout,
                    "gate_stderr": result.stderr[-8000:],
                }, handle, indent=2)

            if result.returncode != 0:
                raise SystemExit(
                    "The model did not load or did not answer. This is the "
                    "failure worth finding here rather than inside a scored run."
                )
            print("The submission's readiness gate passes on real hardware.")
            """
        )
        .replace("BACKEND_LITERAL", build_notebook.ZERX_BACKEND)
        .replace("PLATFORM_LITERAL", build_notebook.ZERX_PLATFORM)
        .replace("MODEL_DIR_LITERAL", build_notebook.KAGGLE_MODEL_DIR or "")
    )

    return {
        "metadata": {
            "kernelspec": {"language": "python", "display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python", "file_extension": ".py"},
            "kaggle": {
                "accelerator": build_notebook._ACCELERATORS[build_notebook.ACCELERATOR]["name"],
                "isInternetEnabled": False,
                "isGpuEnabled": True,
                "language": "python",
                "sourceType": "notebook",
            },
        },
        "nbformat_minor": 4,
        "nbformat": 4,
        "cells": [intro, transformers_cell, mkdir_cell, *zerx_cells,
                  gate_cell, diagnostic_cell, run_cell],
    }


def build_metadata() -> dict:
    submission_meta = json.loads(
        build_notebook.METADATA_PATH.read_text(encoding="utf-8")
    )
    return {
        "id": f"{submission_meta['id'].split('/')[0]}/{KERNEL_SLUG}",
        "title": "zerx — model load smoke",
        "code_file": "model-smoke.ipynb",
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        "enable_gpu": True,
        "enable_tpu": False,
        "enable_internet": False,
        "keywords": [],
        "dataset_sources": [build_notebook.WHEELS_DATASET],
        "kernel_sources": [],
        # The competition IS attached, even though this kernel plays no game.
        #
        # It was left off at first, on the reasoning that a model-load test does
        # not need game data. That cost the run its GPU: the kernel recorded
        # machine_shape=NvidiaRtxPro6000 server-side (confirmed via
        # `kaggle kernels pull -m`) and was still allocated a Tesla P100, while
        # the probe kernel -- same flag, same account, competition attached --
        # got the RTX PRO 6000. The starter's own README says "RTX 6000 is
        # reserved for ARC-AGI-3 notebooks only"; attaching the competition is
        # evidently what makes a kernel one of those.
        "competition_sources": ["arc-prize-2026-arc-agi-3"],
        "model_sources": [build_notebook.MODEL_SOURCE],
    }


def main() -> None:
    SMOKE_DIR.mkdir(parents=True, exist_ok=True)
    NOTEBOOK_PATH.write_text(json.dumps(build(), indent=1), encoding="utf-8")
    METADATA_PATH.write_text(
        json.dumps(build_metadata(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"[build_model_smoke_notebook] Wrote {NOTEBOOK_PATH.relative_to(ROOT)}")
    print(f"[build_model_smoke_notebook] Wrote {METADATA_PATH.relative_to(ROOT)}")
    flag = build_notebook.push_accelerator_flag()
    print(f"[build_model_smoke_notebook] Push with:  kaggle kernels push "
          f"-p notebooks/model-smoke --accelerator {flag}")


if __name__ == "__main__":
    main()
